input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["user-activity", "transactions"]
    codec => json
    group_id => "logstash-ecommerce"
    decorate_events => true
  }
}

filter {
  if [action] {
    mutate { add_field => { "event_type" => "user_activity" } }
  } else if [transaction_id] {
    mutate { add_field => { "event_type" => "transaction" } }
  } else {
    mutate { add_field => { "event_type" => "unknown" } }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["@version", "event"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ecommerce-%{event_type}-%{+YYYY.MM.dd}"
  }
}